# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |rs|
    rs.memory = 2048
    rs.cpus = 2
  end

  # Will not check for box updates during every startup.
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20221213.0.0"
  config.vm.box_check_update = false

  # VM1: Ansible Managerment node where ansible will be installed
  config.vm.define "ubuntu-vm" do |ubuntu|
    ubuntu.vm.hostname = "ubuntu.vm.com"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
	ubuntu.vm.provision "shell", inline: <<-SHELL
	    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      SHELL
  end


end
