# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |rs|
    rs.memory = 2048
    rs.cpus = 2
  end

  # Will not check for box updates during every startup.
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20221213.0.0"
  config.vm.box_check_update = false

  # VM1: Ansible Managerment node where ansible will be installed
  config.vm.define "manager" do |vm1|
    vm1.vm.hostname = "manager.ansible.com"
    vm1.vm.network "private_network", ip: "192.168.56.10"
	  vm1.vm.provision "shell", inline: <<-SHELL
	    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      SHELL
    vm1.vm.provision "shell", path: "../ansible/scripts/bootstrap.sh"
    vm1.vm.provision "file", source: "../ansible/scripts/key_gen.sh", destination: "/home/vagrant/"
    vm1.vm.provision "file", source: "../ansible/k8s", destination: "/home/vagrant/k8s"
  end

  # VM2 : K8S Controller node.
  config.vm.define "controller" do |vm2|
    vm2.vm.hostname = "controller.k8s.com"
    vm2.vm.network "private_network", ip: "192.168.56.11"
	  vm2.vm.provision "shell", inline: <<-SHELL
	    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      SHELL
      vm2.vm.provision "shell", path: "../ansible/scripts/bootstrap.sh"
  end

  # VM3: K8S Worker node 1.
  config.vm.define "worker1" do |vm3|
    vm3.vm.hostname = "worker1.k8s.com"
    vm3.vm.network "private_network", ip: "192.168.56.12"
	  vm3.vm.provision "shell", inline: <<-SHELL
	    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      SHELL
    vm3.vm.provision "shell", path: "../ansible/scripts/bootstrap.sh"
  end
  
  # VM4: K8S Worker node 2.
  config.vm.define "worker2" do |vm4|
    vm4.vm.hostname = "worker2.k8s.com"
    vm4.vm.network "private_network", ip: "192.168.56.13"
	  vm4.vm.provision "shell", inline: <<-SHELL
	    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
	    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      SHELL
    vm4.vm.provision "shell", path: "../ansible/scripts/bootstrap.sh"
  end
end
